# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: Czech Technical University in Prague

# Generates robot model masks for cameras
# Requires https://github.com/ctu-vras/robot_model_renderer in workspace.
# Requires https://github.com/ctu-vras/cv_image_transport in workspace.
out_format: '{name}.mask{ext}'
compression: lz4
filters:
  - Topics:
      include_topics:
        - /tf
        - /tf_static
        - /viz/camera_0/camera_info
        - /viz/camera_1/camera_info
        - /viz/camera_2/camera_info
        - /viz/camera_3/camera_info
        - /viz/camera_4/camera_info
        - /viz/camera_5/camera_info
  - RenderCameraMask:
      camera_info_topic: /viz/camera_0/camera_info
      mask_topic: /viz/camera_0/image/mask
      description_param: nifti_robot_description
  - RenderCameraMask:
      camera_info_topic: /viz/camera_1/camera_info
      mask_topic: /viz/camera_1/image/mask
      description_param: nifti_robot_description
  - RenderCameraMask:
      camera_info_topic: /viz/camera_2/camera_info
      mask_topic: /viz/camera_2/image/mask
      description_param: nifti_robot_description
  - RenderCameraMask:
      camera_info_topic: /viz/camera_3/camera_info
      mask_topic: /viz/camera_3/image/mask
      description_param: nifti_robot_description
  - RenderCameraMask:
      camera_info_topic: /viz/camera_4/camera_info
      mask_topic: /viz/camera_4/image/mask
      description_param: nifti_robot_description
  - RenderCameraMask:
      camera_info_topic: /viz/camera_5/camera_info
      mask_topic: /viz/camera_5/image/mask
      description_param: nifti_robot_description
  - CompressImages:
      transport: cv
      transport_params:
        cv:
          format: pbm
  - Remap:
      /viz/camera_0/image/mask/cv: /viz/camera_0/image/mask/compressed
      /viz/camera_1/image/mask/cv: /viz/camera_1/image/mask/compressed
      /viz/camera_2/image/mask/cv: /viz/camera_2/image/mask/compressed
      /viz/camera_3/image/mask/cv: /viz/camera_3/image/mask/compressed
      /viz/camera_4/image/mask/cv: /viz/camera_4/image/mask/compressed
      /viz/camera_5/image/mask/cv: /viz/camera_5/image/mask/compressed
  - Drop:
      include_topics:
        - /tf
        - /tf_static
        - /viz/camera_0/camera_info
        - /viz/camera_1/camera_info
        - /viz/camera_2/camera_info
        - /viz/camera_3/camera_info
        - /viz/camera_4/camera_info
        - /viz/camera_5/camera_info