out_format: '{name}.cams_compressed{ext}'
compression: lz4
filters:
  - CompressImages:
      include:
        - /spot/camera/back/image
        - /spot/camera/frontleft/image
        - /spot/camera/frontright/image
        - /spot/camera/left/image
        - /spot/camera/right/image
        - /spot/camera/hand_color/image
        - /spot/camera/hand_mono/image
        - /spot/depth/back/image
        - /spot/depth/frontleft/image
        - /spot/depth/frontleft/depth_in_visual
        - /spot/depth/frontright/image
        - /spot/depth/frontright/depth_in_visual
        - /spot/depth/left/image
        - /spot/depth/right/image
        - /spot/depth/hand/depth_in_color
        - /spot/depth/hand/image
      compression_levels:
        jpg: 90
        png: 5
