#!/usr/bin/env python

from __future__ import print_function

import sys
from rosbag.bag import Bag

from cras_bag_tools.fix_msg_defs import fix_msg_defs


if __name__ == '__main__':

    if len(sys.argv) <= 1:
        print("Fix message definitions in a bag file according to local definitions", file=sys.stderr)
        print("Usage: bag_fix_msg_defs bag [topic [topic ...]]", file=sys.stderr)
        sys.exit(1)

    bag_file = sys.argv[1]
    topics = sys.argv[2:]

    with Bag(bag_file, mode='a', skip_index=True) as bag:
        fix_msg_defs(bag, topics)

    # the bag is autosaved when closed
