#!/usr/bin/env python

from __future__ import print_function

import rospy
from roslib.message import get_message_class

pub = None
last_msg = None
timer = None


def cb(msg):
    global pub
    global last_msg
    global timer
    last_msg = msg
    if pub is None:
        cls = get_message_class(msg._connection_header['type'])
        pub = rospy.Publisher("out", cls, queue_size=10)
        timer = rospy.Timer(rospy.Rate(rate).sleep_dur, timer_cb)
    pub.publish(msg)


def timer_cb(event):
    if last_msg is not None and pub is not None:
        pub.publish(last_msg)


if __name__ == "__main__":
    rospy.init_node('repeat', anonymous=True)
    rate = rospy.get_param("~rate", 1.0)
    sub = rospy.Subscriber('in', rospy.AnyMsg, cb, queue_size=10)
    rospy.spin()
